"""篩選參數與路徑設定。調整選股條件只需要改這個檔案。"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE_DIR = ROOT / "cache"
SITE_DIR = ROOT / "site"

QUOTE_CACHE = CACHE_DIR / "quotes.parquet"
VALUATION_CACHE = CACHE_DIR / "valuation.parquet"

# 歷史深度
QUOTE_HISTORY_DAYS = 180
VALUATION_HISTORY_DAYS = 365 * 3

# 對外請求
REQUEST_DELAY_SEC = 1.2
REQUEST_RETRIES = 3
REQUEST_TIMEOUT_SEC = 60

# 流動性門檻
MIN_AVG_VOLUME_LOTS = 500
MIN_TRADING_DAYS = 60

# 基本面條件
PE_PERCENTILE_MAX = 40.0
PE_ABSOLUTE_MAX = 25.0
PB_PERCENTILE_MAX = 50.0
MIN_DIVIDEND_YIELD = 2.0

# 技術面條件
MA_SHORT = 20
MA_LONG = 60
MA_SLOPE_LOOKBACK = 5
VOLUME_SURGE_RATIO = 1.5
VOLUME_SURGE_WINDOW = 5
BREAKOUT_WINDOW = 60
BREAKOUT_TOLERANCE = 0.98

# 入選門檻
MIN_FUNDAMENTAL_PASSES = 4
MIN_TECHNICAL_PASSES = 3

FUNDAMENTAL_TOTAL = 5
TECHNICAL_TOTAL = 4

STAR_THRESHOLDS = [(9, 5), (8, 4), (7, 3)]
STAR_DEFAULT = 2
